### ISSUE TITLE
No captura totes les referències

### ISSUE THREAD

**Issue by ctrl-alt-d** [kastwey/TestBlazorReference#1]
### Problema:

Quan s'executa el programa, en clicar els botons, no es capturen **totes** les referències. 

Penso que això és degut a l'algoritme de refresc, l'algoritme fa un "diff" del que hi havia abans respecte del que ha de pintar ara i només repinta diferències. Els elements que no es repinten no captura referències i aquí hi ha el problema. Sospito que de la llista de 100 no en captura cap, perquè considera que pot "reciclar" elements de la llista de 1000. I de la llista de 1000 només en captura 900, perquè considera que en pot "reciclar" 100 de l'anterior llista.

#### Opció 1: Forçar que s'esborri completament una llista abans de pintar la següent.

Ho faríem posant `_gridRows` a `null`, enviant a la ui i només després enviar la nova llista:

```c#
public async Task RenderGrid1()
{
	_gridRows = null;
	await Task.Delay(1);
	_gridRows = _firstRows;
}

public async Task RenderGrid2()
{
	_gridRows = null;
	await Task.Delay(1);
	_gridRows = _secondRows;
}
```

#### Opció 2 (més elegant): ajudar a l'algoritme de diff a identificar els canvis.

Ho faríem afegint una `@key` a cada `GridRow`:

```razor
@foreach (var row in _items)
{
    <GridRow Model="@row.Model" @ref="row.Row" @key="@row.Model.Id" ></GridRow>
}
```

Espero que això solucioni el problema :)

**Comment by kastwey** [comment]
Thanks so much!!! 👍
